```{r}
library(ggplot2)
library(tidyverse)
```



```{r, label='plotting with ggplot; import dataset, etc'}
plt <- ggplot(mpg, aes(x=class)) # import

```

```{r, label='plot the thing'}
plt + geom_bar()
```
```{r, label='plot vehicle count by manufacturer with summarize()'}
# create the summary table
mpg_summary <- mpg %>% group_by(manufacturer) %>% summarize(Vehicle_Count=n(), .groups = 'keep')
```

```{r, label='plot the summary table'}
# plot dataframe created above
plt <- ggplot(mpg_summary,aes(x=manufacturer, y=Vehicle_Count))
plt + geom_col()
```


```{r,label='format chart'}
plt + geom_col() + xlab("Manufacturing Company") + ylab("Number of Vehicles") + #plot a boxplot with labels
theme(axis.text.x=element_text(angle=45,hjust=1)) #rotate the x-axis label 45 degrees
```

```{r, label='line plot'}
mpg_summary <- subset(mpg,manufacturer=="toyota") %>% group_by(cyl) %>% summarize(Mean_Hwy=mean(hwy), .groups = 'keep') #create summary table
plt <- ggplot(mpg_summary,aes(x=cyl,y=Mean_Hwy)) #import dataset into ggplot2
plt + geom_line() + scale_x_discrete(limits=c(4,6,8)) + scale_y_continuous(breaks = c(15:30)) #add line plot with labels

```

```{r,label='scatter'}
# size of car engine vs city mpg
plt <- ggplot(mpg,aes(x=displ,y=cty,color=class,shape=drv,size=cty)) #import dataset into ggplot2
plt + geom_point() + xlab("Engine Size (Liters)") + ylab("City Fuel Efficiency (MPG)")
```

```{r,label='box plots'}
plt <- ggplot(mpg,aes(y=hwy)) #import dataset into ggplot2
plt + geom_boxplot() #add boxplot
```

```{r}
plt <- ggplot(mpg,aes(x=manufacturer,y=hwy,color=manufacturer)) #import dataset into ggplot2
plt + geom_boxplot(show.legend = F, outlier.colour = "black", outlier.shape = 1, linetype = "dotted") + theme(axis.text.x=element_text(angle=45,hjust=1)) #add boxplot and rotate x-axis labels 45 degrees
```


```{r, label='heat map'}
#create summary table
mpg_summary <- mpg %>% group_by(class,year) %>% summarize(Mean_Hwy=mean(hwy), .groups = 'keep') 

plt <- ggplot(mpg_summary, aes(x=class,y=factor(year),fill=Mean_Hwy))

#create heatmap with labels
plt + geom_tile() + labs(x="Vehicle Class",y="Vehicle Year",fill="Mean Highway (MPG)") 
```


```{r}
#create summary table
mpg_summary <- mpg %>% group_by(model,year) %>% summarize(Mean_Hwy=mean(hwy), .groups = 'keep') 

plt <- ggplot(mpg_summary, aes(x=model,y=factor(year),fill=Mean_Hwy)) #import dataset into ggplot2

#add heatmap with labels 
plt + geom_tile() + labs(x="Model",y="Vehicle Year",fill="Mean Highway (MPG)") + theme(axis.text.x = element_text(angle=90,hjust=1,vjust=.5)) #rotate x-axis labels 90 degrees

```

```{r, label='LAYERS'}
#import dataset into ggplot2
plt <- ggplot(mpg,aes(x=manufacturer,y=hwy)) 

#add boxplot, rotate x-axis labels 45 degrees, and overlay scatter plot on top
plt + geom_boxplot() + theme(axis.text.x=element_text(angle=45,hjust=1)) + 
geom_point() 
```

```{r}
mpg_summary <- mpg %>% group_by(class) %>% summarize(Mean_Engine=mean(displ), .groups = 'keep')

plt <- ggplot(mpg_summary,aes(x=class,y=Mean_Engine))

plt + geom_point(size=4) + labs(x="Vehicle Class",y="Mean Engine Size")
```

```{r}
mpg_summary <- mpg %>% group_by(class) %>% summarize(Mean_Engine=mean(displ),SD_Engine=sd(displ), .groups = 'keep')

plt <- ggplot(mpg_summary,aes(x=class,y=Mean_Engine))

plt + geom_point(size=4) + labs(x="Vehicle Class",y="Mean Engine Size") + geom_errorbar(aes(ymin=Mean_Engine-SD_Engine,ymax=Mean_Engine+SD_Engine))
```
```{r,label='long format faceting'}
mpg_long <- mpg %>% gather(key="MPG_Type",value="Rating",c(cty,hwy))
```

```{r}
plt <- ggplot(mpg_long,aes(x=manufacturer,y=Rating,color=MPG_Type))

plt + geom_boxplot() + theme(axis.text.x=element_text(angle=45,hjust=1))
```

```{r,label='use facet_wrap to create two box plots with facets'}
plt <- ggplot(mpg_long,aes(x=manufacturer,y=Rating,color=MPG_Type))

#create multiple boxplots, one for each MPG type
plt + geom_boxplot() + facet_wrap(vars(MPG_Type)) + theme(axis.text.x=element_text(angle=45,hjust=1),legend.position = "none") + xlab("Manufacturer")
```

```{r, label='QUALITATIVE TEST FOR NORMALITY'}
# visually assess shape and distribution of data
ggplot(mtcars,aes(x=wt)) + geom_density()

```

```{r, label='QUANTITATIVE TEST FOR NORMALITY'}
# quantitative test of whether or not the test data came from a normally distributed data set
shapiro.test(mtcars$wt)
```

```{r, label='SAMPLING DATASET'}
# first visualize distribution of data
population_table <- read.csv('used_car_data.csv',check.names = F,stringsAsFactors = F)

plt <- ggplot(population_table,aes(x=log10(Miles_Driven)))

plt + geom_density()

```

```{r, label = 'SAMPLE DATA WITH SAMPLE_N()'}
# randomly select 50 data points from population_table
sample_table <- population_table %>% sample_n(50)

plt <- ggplot(sample_table,aes(x=log10(Miles_Driven)))

plt + geom_density()
```

```{r, label = 'ONE SAMPLE T-TEST'}
# one of the most basic and popular stats tests in the world. Used to compare one dataset mean to another w/ some assumptions
t.test(log10(sample_table$Miles_Driven),mu=mean(log10(population_table$Miles_Driven)))

# P-VALUE IS HIGH, SO TWO MEANS OF RESPECTIVE DATASETS ARE STATISTICALLY SIMILAR**********
```

```{r, label = 'TWO SAMPLE T-TEST'}
# compares TWO sample means to one another to determine if they are statistically different
sample_table <- population_table %>% sample_n(50)

sample_table2 <- population_table %>% sample_n(50)

t.test(log10(sample_table$Miles_Driven),log10(sample_table2$Miles_Driven))
```

```{r, label = 'PAIR T-TEST'}
# use two-sample t-test to compare samples from TWO different populations
mpg_data <- read.csv('mpg_modified.csv')
mpg_1999 <- mpg_data %>% filter(year==1999)
mpg_2008 <- mpg_data %>% filter(year==2008)

t.test(mpg_1999$hwy,mpg_2008$hwy,paired = T)
```

```{r, label='ANOVA TEST'}
# Analysis of Variance compares means of a continuous numerical variables across a number of groups
# One-way ANOVA: test the means of 1 independent var across 1 independent var w/ multiple groups
# Two-way ANOVA: same thing, but for 2 independent vars

mtcars_filt <- mtcars[,c("hp", "cyl")] # filter columns from dataset
mtcars_filt$cyl <- factor(mtcars_filt$cyl) # convert numeric column to factor

summary(aov(hp ~ cyl,data = mtcars_filt))

## Results show a p-value of .0000000132, which means we can reject the null hypothesis and say that there is a statistically significant difference in hp between at least 1 engine type compared to others.
```

```{r, label = 'CORRELATION COEFFICIENT'}
plt <- ggplot(mtcars,aes(x=hp,y=qsec))
plt + geom_point()

# RESULTS: negative correlation between quarter-mile time and horsepower (hp increases as qsec decreases)
```


```{r}
cor(mtcars$hp,mtcars$qsec)

# STRONG NEGATIVE CORRELATION
```


```{r}
used_cars <- read.csv('used_car_data.csv',stringsAsFactors = F)
head(used_cars)
```


```{r}
# Are miles driven and selling price correlated?
plt <- ggplot(used_cars,aes(x=Miles_Driven,y=Selling_Price))
plt + geom_point()
```


```{r}
cor(used_cars$Miles_Driven,used_cars$Selling_Price)

# RESULTS: Negligible correlation 
```


```{r, label = 'USE CORRELATION MATRIX'}
# correlation matrix allows us to see the correlation coefficients as rows/cols of the dataset base on user input of dataset columns
used_matrix <- as.matrix(used_cars[,c("Selling_Price","Present_Price","Miles_Driven")])
cor(used_matrix)
```


```{r, label = 'LINEAR REGRESSION'}
lm(qsec ~ hp,mtcars)
# linear regression model for this would be: qsec = -0.02 + 20.56
```


```{r}
# summary of linear regression model
summary(lm(qsec ~ hp,mtcars))


# RESULTS: multiple R-squared = .5016 meaning 50% of dependent var (qsec) explained with this linear model.
# p-value = 0.00000577, slope is NOT zero and can reject null hypothesis.
```


```{r, label = 'visualize linear regression line over scatter'}
# creare linear model
model <- lm(qsec ~ hp,mtcars)

# determine y-axis values from linear model
yvals <- model$coefficients['hp']*mtcars$hp + model$coefficients['(Intercept)']

plt <- ggplot(mtcars,aes(x=hp,y=qsec))
plt + geom_point() + geom_line(aes(y=yvals), color='red')
```

```{r, label = 'MULTIPLE LINEAR REGRESSION'}
lm(qsec ~ mpg + disp + drat + wt + hp,data=mtcars)
summary(lm(qsec ~ mpg + disp + drat + wt + hp,data=mtcars))
```

